# Basic application configuration                                            #
MCR.NameOfProject=thowl
MIR.projectid.default=thowl

MCR.Metadata.Languages=de,en

#MCR.PI.Service.Datacite=org.mycore.pi.doi.MCRDOIService
MCR.PI.Service.Datacite.MetadataService=MODSDOI

# Does that DOI is only set after document is published, should be standard behavior
MCR.PI.Service.Datacite.RegistrationPredicate=org.mycore.pi.condition.MCRPIPublishedPredicate
MCR.PI.Service.Datacite.Transformer=datacite
MCR.PI.Service.Datacite.Generator=org.mycore.pi.MCRGenericPIGenerator

MCR.PI.Generator.Datacite.GeneralPattern=%MCR.DOI.Prefix%/$ObjectDate-$Count
MCR.PI.Generator.Datacite.DateFormat=yyyy
MCR.PI.Generator.Datacite.CountPrecision=3

MCR.PI.MetadataService.MODSDOI=org.mycore.mods.identifier.MCRMODSDOIMetadataService
MCR.PI.MetadataService.MODSDOI.Type=doi
MCR.PI.Parsers.doi=org.mycore.pi.doi.MCRDOIParser

# OAI Data Provider                                                          #
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml

# MIR ePuSta                                                                 #
# show ePuSta Statistics in metadata view ('show', 'hide')
MIR.ePuSta=hide


# Editor                                                                     #
# Customization of XEditor forms
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed

# Frontend                                                                     #
MIR.CustomLayout.JS=thowl.js

# Set mcr_error properties in your mycore.properties.private to show OA error page without StackTrace
MCR.ContentTransformer.mcr_error.Stylesheet=xsl/errorPage.xsl,%MCR.LayoutTransformerFactory.Default.Stylesheets%

# Disable Servlets                                                           #
MCR.Servlet.MirSelfRegistrationServlet.Disabled=true
